## Output name and relevant info
export NAME=APPKI_mouse
export SPECIES=mm10

# sequencing mode: <targeted> <whole>
export SEQUENCING=whole

# if multiplexing was performed
export MULTIPLEXING=TRUE

# specify if de-multiplexing is required
export DEMULTIPEX=FALSE

# specify whether to merge fastq files in demultiplexed folders
export MERGE_FASTQ=TRUE

## Output root directory filepath (ensure path exists)
export SCRIPT_ROOT=/lustre/projects/Research_Project-MRC148213/fergus/LRPipeline/ont_cDNA
export WKD_ROOT=/lustre/projects/Research_Project-MRC148213/fergus/output
export META_ROOT=/lustre/projects/Research_Project-MRC148213/fergus/metadata

## SKLeung scripts
export LOGEN_ROOT=//lustre/projects/Research_Project-MRC148213/fergus/LOGen

export DEMULTIPLEX_DIR=/lustre/projects/Research_Project-MRC190311/longReadSeq/ONTRNA/Mouse/APPKI/0_raw/Batch2
export DEMULTIPLEX_SOFTWARE=Pychopper
## ---------------------------

## Reference data filepaths - located in lsl693, but i have access.
export GENOME_FASTA=/lustre/projects/Research_Project-MRC148213/lsl693/references/mouse/mm10.fa
export GENOME_GTF=/lustre/projects/Research_Project-MRC148213/lsl693/references/annotation/gencode.vM22.annotation.gtf                   

## ---------------------------

# number of total samples (across all flow cells)
export numSamples=8

## ONT raw data
# sequentially specify paths of raw fastq files from multiple flow cells
export RAW_ROOT_DIR=/lustre/projects/Research_Project-MRC190311/longReadSeq/ONTRNA/Mouse/APPKI/0_raw/Batch2


# export barcode (if multiplexing=TRUE) <barcode number> <sample name>
BARCODE_CONFIG=${SCRIPT_ROOT}/config/barcode.csv
export ALL_SAMPLES_NAMES=($(awk -F "\"*,\"*" '{print $1}' ${BARCODE_CONFIG}))

# sample names to replace barcode names downstream 
SAMPLE_ID=${SCRIPT_ROOT}/config/sample_id.csv

## ---------------------------

## Software  - located in lsl693, using szi kays dir for software, could change to mine.
export SOFTDIR=/lustre/projects/Research_Project-MRC148213/lsl693/software

export MINIONQC=${SOFTDIR}/minion_qc/MinIONQC.R
# to run Porechop, require gcc-version 4.9.1 or more; 
# on Knight: git clone https://github.com/rrwick/Porechop.git; cd Porechop; make
# transfer whole Porechop folder from Knight to ISCA, and chmod 
export PORECHOP=${SOFTDIR}/Porechop/porechop-runner.py
export TCLEAN=${SOFTDIR}/TranscriptClean/TranscriptClean.py
export CUPCAKE=${SOFTDIR}/cDNA_Cupcake
export ANNOTATION=$CUPCAKE/annotation
export SEQUENCE=$CUPCAKE/sequence
export PYTHONPATH=$PYTHONPATH:$SEQUENCE
export SQANTI3_DIR=${SOFTDIR}/SQANTI3
export SQANTI_JSON=/lustre/projects/Research_Project-MRC190311/scripts/sequencing/longReadseq/SQANTI3-5.1/SQANTI3-5.1/utilities/filter/filter_adapted.json

## ---------------------------

## Software input files
# SQANTI3 input files
CAGE_PEAK=$SQANTI3_DIR/data/ref_TSS_annotation/human.refTSS_v3.1.hg38.bed
POLYA=$SQANTI3_DIR/data/polyA_motifs/mouse_and_human.polyA_motif.txt


## ---------------------------
cd ${WKD_ROOT}
mkdir -p 1_demultiplex 1b_demultiplex_merged 2_cutadapt_merge 3_minimap 4_tclean 5_cupcake
mkdir -p ${WKD_ROOT}/1_demultiplex/Batch2 ${WKD_ROOT}/5_cupcake/5_align
mkdir -p $WKD_ROOT/5_cupcake/5_align/combined $WKD_ROOT/5_cupcake/6_collapse $WKD_ROOT/5_cupcake/5_align/combined_fasta $WKD_ROOT/5_cupcake/7_sqanti3
